added change to tasks file and all tests
adsabs/ADSOrcid pull request #106
Opened 2023-07-18 16:46 UTC by femalves

2023-07-18 16:49 UTC, femalves commented
https://github.com/actions/setup-python/issues/672 
"Breaking changes
Hello everyone. The Python 2.7.x will be removed from [python-versions](https://github.com/actions/python-versions) and it won't be possible to set up Python 2.7.x by setup-python.

The motivation for the changes
Python2.7 is not [supported](https://www.python.org/doc/sunset-python-2/) since January 1, 2020."

2023-07-18 17:44 UTC, tjacovich commented
To update the tests to `python3`
This section in the `python-actions.yaml` [file](https://github.com/adsabs/ADSOrcid/blob/dc50c78e29f58e31064c52b265fc8c82a6b2bdfe/.github/workflows/python_actions.yml#L12C1-L14C28)
```
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 2.7
```

Should become:
```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
```

2023-07-19 15:00 UTC, tjacovich requested changes
Overall looks good. Just a couple of formatting things and the update to the github action.

2023-07-19 19:19 UTC, femalves commented on requirements.txt
> +matplotlib==3.5.0 #2.0.2 is not compatible with Python 3.8
Yup. Thanks for the reminder. Done!

2023-07-26 16:27 UTC, tjacovich reviewed
This looks good to me. Just one incredibly small potential tweak in `tasks.py` and then one potential test tweak. It looks like one of the assert methods used in the tests for `models.py` has been deprecated. Would you be willing to incorporate that fix into this PR?

One of the offending lines (it looks like there might be two of them in total):
```
ADSOrcid/tests/test_models.py::Test::test_models
  /home/runner/work/ADSOrcid/ADSOrcid/ADSOrcid/tests/test_models.py:61: DeprecationWarning: Please use assertRaisesRegex instead.
    with self.assertRaisesRegexp(Exception, 'IntegrityError'):
```

2023-07-28 13:59 UTC, tjacovich approved these changes

2023-07-28 16:51 UTC, merged